name: terminate_restart
description: A Flutter plugin for app termination and restart with data clearing options.
version: 1.0.5
homepage: https://github.com/sleem2012/terminate_restart
repository: https://github.com/sleem2012/terminate_restart
issue_tracker: https://github.com/sleem2012/terminate_restart/issues
documentation: https://github.com/sleem2012/terminate_restart/blob/main/README.md

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ahmedsleem.terminate_restart
        pluginClass: TerminateRestartPlugin
      ios:
        pluginClass: TerminateRestartPlugin

topics:
  - restart
  - terminate
  - process-management
  - app-lifecycle
  - data-clearing
